services:
  addition-service:
    image: raghugannaram/addition-service:1.0.0
    ports:
      - "9001:9001"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./_docker/addition_service/logs:/app/logs

  subtraction-service:
    image: raghugannaram/subtraction-service:1.0.0
    ports:
      - "9002:9002"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./_docker/subtraction_service/logs:/app/logs

  multiplication-service:
    image: raghugannaram/multiplication-service:1.0.0
    ports:
      - "9003:9003"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./_docker/multiplication_service/logs:/app/logs

  division-service:
    image: raghugannaram/division-service:1.0.0
    ports:
      - "9004:9004"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./_docker/division_service/logs:/app/logs

  calculation-service:
    image: raghugannaram/calculation-service:1.0.0
    ports:
      - "9000:9000"
    environment:
      - LOG_LEVEL=debug
    volumes:
      - ./_docker/calculation_service/logs:/app/logs
    depends_on:
      - addition-service
      - subtraction-service
      - multiplication-service
      - division-service